server:
  port: 8080
  session:
    timeout: 1800
  tomcat: 
    max-threads: 1000
    min-spare-threads: 200
    accept-count: 1000
    max-connections: 1000
    
 # connection-timeout: 60
 
spring:
   datasource: 
     name: master
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/seven_seconds_db
     username: root
     password: liliu 
   redis:
     host: 127.0.0.1
     password: liliu
     port: 6379 
     database: 1
     timeout: 3000
     pool: 
       min-idle: 100
       max-idle: 300
       max-active: 800 
myPugin: 
  session: 
    myDomainName: null
  projectName: SevenSeconds
  pushStoreDomainUrl: http://localhost:8002
  bookStoreDomainUrl: http://localhost:8082
  location: c://config/thirdParty.properties
  articleUrl: http://localhost/article.html
  shareUrl: http://localhost/share.html
  shareDomain: localhost
  gmwDomain: localhost
  ssDomain: localhost
  adDomain: localhost
  jsAd: console.log('dev')
  requestAuth: requestAuthDev
  rabbitmq:
    ARTICLECLICK_DIRECT_EXCHANGE: test.articleclick.sevenseconds.exchange.direct
    ARTICLECLICK_DIRECT_ROUTINGKEY: test.articleclick.sevenseconds.routingkey.direct
    ARTICLECLICK_DIRECT_QUEUE: test.articleclick.sevenseconds.queue.direct
    ARTICLEREAD_DIRECT_EXCHANGE: test.articleread.sevenseconds.exchange.direct
    ARTICLEREAD_DIRECT_ROUTINGKEY: test.articleread.sevenseconds.routingkey.direct
    ARTICLEREAD_DIRECT_QUEUE: test.articleread.sevenseconds.queue.direct
    ARTICLEWEBREAD_DIRECT_EXCHANGE: test.articlewebread.sevenseconds.exchange.direct
    ARTICLEWEBREAD_DIRECT_ROUTINGKEY: test.articlewebread.sevenseconds.routingkey.direct
    ARTICLEWEBREAD_DIRECT_QUEUE: test.articlewebread.sevenseconds.queue.direct
    COMMENT_DIRECT_EXCHANGE: test.comment.sevenseconds.exchange.direct
    COMMENT_DIRECT_ROUTINGKEY: test.comment.sevenseconds.routingkey.direct
    COMMENT_DIRECT_QUEUE: test.comment.sevenseconds.queue.direct
    REPLY_DIRECT_EXCHANGE: test.reply.sevenseconds.exchange.direct
    REPLY_DIRECT_ROUTINGKEY: test.reply.sevenseconds.routingkey.direct
    REPLY_DIRECT_QUEUE: test.reply.sevenseconds.queue.direct
    BARRAGE_DIRECT_EXCHANGE: test.barrage.sevenseconds.exchange.direct
    BARRAGE_DIRECT_ROUTINGKEY: test.barrage.sevenseconds.routingkey.direct
    BARRAGE_DIRECT_QUEUE: test.barrage.sevenseconds.queue.direct
    COMPLAIN_DIRECT_EXCHANGE: test.complain.sevenseconds.exchange.direct
    COMPLAIN_DIRECT_ROUTINGKEY: test.complain.sevenseconds.routingkey.direct
    COMPLAIN_DIRECT_QUEUE: test.complain.sevenseconds.queue.direct
    SIGN_DIRECT_EXCHANGE: test.sign.sevenseconds.exchange.direct
    SIGN_DIRECT_ROUTINGKEY: test.sign.sevenseconds.routingkey.direct
    SIGN_DIRECT_QUEUE: test.sign.sevenseconds.queue.direct
    NOVICETASK_DIRECT_EXCHANGE: test.novicetask.sevenseconds.exchange.direct
    NOVICETASK_DIRECT_ROUTINGKEY: test.novicetask.sevenseconds.routingkey.direct
    NOVICETASK_DIRECT_QUEUE: test.novicetask.sevenseconds.queue.direct
    DAILYTASK_DIRECT_EXCHANGE: test.dailytask.sevenseconds.exchange.direct
    DAILYTASK_DIRECT_ROUTINGKEY: test.dailytask.sevenseconds.routingkey.direct
    DAILYTASK_DIRECT_QUEUE: test.dailytask.sevenseconds.queue.direct
    MERORDERFLOWWATER_DIRECT_EXCHANGE: test.merorderflowwater.convertmall.exchange.direct
    MERORDERFLOWWATER_DIRECT_ROUTINGKEY: test.merorderflowwater.convertmall.routingkey.direct
    MERORDERFLOWWATER_DIRECT_QUEUE: test.merorderflowwater.convertmall.queue.direct
    BOOKORDERFLOWWATER_DIRECT_EXCHANGE: test.bookorderflowwater.bookstore.exchange.direct
    BOOKORDERFLOWWATER_DIRECT_ROUTINGKEY: test.bookorderflowwater.bookstore.routingkey.direct
    BOOKORDERFLOWWATER_DIRECT_QUEUE: test.bookorderflowwater.bookstore.queue.direct
  alibabaSmsAppkey: 23431362
  alibabaSmsAppsecret: dfbbbfe72864929214f23f48c901a638
  alibabaSmsSignName: 雅耀
  alibabaSmsTemplateCodeAcountRegister: SMS_13026946
  alibabaSmsTemplateCodePasswordUpdate: SMS_13026944
  aliyunSmsAppkey: LTAIgDJerZxD8twJ
  aliyunSmsAppsecret: 9PuLZNoEQRPDJm465MxL1JIXQY9Msh
  aliyunSmsSignName: 七秒资讯
  aliyunSmsTemplateCodeAcountRegister: SMS_89885232
  aliyunSmsTemplateCodePasswordUpdate: SMS_89885231